In [1]:
import pandas as pd

In [2]:
baseline_df = pd.read_json('../data/baseline_PMC12.json')

In [3]:
baseline_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 97909 entries, 0 to 97908
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   article-type  97909 non-null  object
 1   language      77838 non-null  object
 2   journal       97909 non-null  object
 3   pmc-id        97909 non-null  object
 4   title         97904 non-null  object
 5   country       96012 non-null  object
 6   date          97909 non-null  object
 7   abstract      97909 non-null  object
dtypes: object(8)
memory usage: 6.7+ MB

In [4]:
baseline_df.head()

,article-type,language,journal,pmc-id,title,country,date,abstract
0,brief-report,None,Forensic Science International: Synergy,PMC12005907,Technical Note: A comparison of solvents for o...,UK,07-4-2025,Passive sampling techniques such as sticky tra...
1,research-article,en,Molecules,PMC12156393,Egyptian Blue into Carboxymetylcellulose: New ...,(M.C.);,28-5-2025,The development and characterization of a sust...
2,research-article,en,Behavioral Sciences,PMC12108589,A Path Out: Using Video Games to Reduce Prejud...,gray.atherton@plymouth.ac.uk,26-4-2025,"Historically, research on video games has cent..."
3,research-article,en,International Journal of Molecular Sciences,PMC12072557,Neanderthal and Denisovan Glutamate Dehydrogen...,vjulia94@gmail.com,01-5-2025,Mammalian glutamate dehydrogenase (GDH) is an ...
4,research-article,en,Frontiers in Immunology,PMC12089083,Characterization and correlation analysis of o...,China,06-5-2025,Introduction Changes in oral neutrophil number...

In [5]:
no_country = baseline_df[baseline_df['country'].isnull()]

In [6]:
no_country.sort_values('pmc-id').head()

,article-type,language,journal,pmc-id,title,country,date,abstract
33863,abstract,en,Learning Health Systems,PMC12000759,2024 Advances in Learning Health System Scienc...,None,17-2-2025,
63891,correction,en,Oncology Letters,PMC12000797,[Corrigendum] lncRNA SNHG3 acts as oncogene in...,None,08-4-2025,
48683,research-article,en,Journal of machine learning research : JMLR,PMC12000818,Dimension-Grouped Mixed Membership Models for ...,None,2-2023,Mixed Membership Models (MMMs) are a popular f...
42963,research-article,en,EFSA Journal,PMC12000819,Safety and efficacy of a feed additive consist...,None,16-4-2025,Abstract Following a request from the European...
24742,research-article,en,EFSA Journal,PMC12000820,Assessment of the feed additive consisting of ...,None,16-4-2025,Abstract Following a request from the European...