In [1]:
import pandas as pd
import re
from collections import Counter
import seaborn as sns

%load_ext autoreload
%autoreload 2
import src.title_versions as tv

In [2]:
baseline_df = pd.read_json('../data/baseline_2025-06-26/PMC008xxxxxx_noncomm.json')

In [3]:
baseline_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 185530 entries, 0 to 185529
Data columns (total 11 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   article-type    185530 non-null  object
 1   language        92879 non-null   object
 2   journal         185530 non-null  object
 3   pmc-id          185530 non-null  object
 4   pmid            155910 non-null  float64
 5   title           185523 non-null  object
 6   country         160471 non-null  object
 7   date            185530 non-null  object
 8   abstract        185530 non-null  object
 9   section_titles  170086 non-null  object
 10  sections        185530 non-null  object
dtypes: float64(1), object(10)
memory usage: 17.0+ MB

In [4]:
baseline_df.head()

,article-type,language,journal,pmc-id,pmid,title,country,date,abstract,section_titles,sections
0,correction,None,Diabetes Therapy,PMC8991299,35286609.0,Correction to: Overt Diabetes in Pregnancy,India,14-3-2022,,[Correction to: Diabetes Ther 10.1007/s13300-0...,[Correction to: Diabetes Ther 10.1007/s13300-0...
1,research-article,en,International Journal of Chronic Obstructive P...,PMC8749770,35027824.0,Effect of Smoking and Its Cessation on the Tra...,India,05-1-2022,Rationale Smoking is the primary cause of chro...,"[Introduction, Methods, Results, Discussion, C...",[Introduction Chronic Obstructive Pulmonary Di...
2,research-article,en,Journal of Clinical Laboratory Analysis,PMC8605134,34528313.0,Evaluation of fungal contamination and ochrato...,"Iran, Islamic Republic of",15-9-2021,Abstract Background Mycotoxins are secondary f...,"[INTRODUCTION, MATERIALS, RESULT, DISCUSSION, ...",[1 INTRODUCTION Coffee is a member of Coffea g...
3,review-article,en,International Journal of Clinical Pediatric De...,PMC8783216,NaN,The Epiphany of Post-COVID: A Watershed for Pe...,India,Nov-Dec-2021,A bstract Coronavirus disease-2019 (COVID-19) ...,"[I, E, T, S, D, C]",[I ntroduction Coronavirus disease-2019 (COVID...
4,research-article,None,Schizophrenia Research: Cognition,PMC8131976,34026572.0,Screening for cognitive impairment in schizoph...,Austria,12-5-2021,Background The Screen for Cognitive Impairment...,"[Introduction, Methods and materials, Results,...",[1 Introduction Cognitive impairment is consid...

In [5]:
#replace None with empty string to make my life easier
baseline_df['section_titles'] = baseline_df['section_titles'].apply(
    lambda x: [] if x == None else x
)

In [16]:
baseline_df[baseline_df['section_titles'].apply(lambda x: not x == None  and 'Expected outcomes' in x)]

,article-type,language,journal,pmc-id,pmid,title,country,date,abstract,section_titles,sections,section_titles_cleaned
27,research-article,None,STAR Protocols,PMC8384916,34467229.0,Induction of granule and Purkinje cells from p...,France,18-8-2021,Summary The architecturally stereotypical stru...,"[Before you begin, Key resources table, Materi...",[Before you begin The following protocol descr...,[limitations]
70,research-article,None,STAR Protocols,PMC8369072,34430916.0,Electrophysiological and anatomical characteri...,Japan,13-8-2021,"Summary In the central nervous system, develop...","[Before you begin, Key resources table, Materi...",[Before you begin Structures and functions of ...,[limitations]
232,research-article,None,STAR Protocols,PMC8273411,34286292.0,Building predictive signaling models by pertur...,United States of America,07-7-2021,Summary This protocol provides a step-by-step ...,"[Before you begin, Key resources table, Materi...",[Before you begin Timing: 1 day Cells in their...,[limitations]
243,research-article,None,STAR Protocols,PMC8689352,34977685.0,Purification and preparation of Rhodobacter s...,Canada,16-12-2021,Summary The formation of defined surfaces cons...,"[Before you begin, Key resources table, Materi...","[Before you begin In this protocol, we begin w...",[limitations]
567,research-article,None,STAR Protocols,PMC8044720,33870228.0,Protocol for building a cognitive map of struc...,United States of America,30-3-2021,Summary Humans are adept at learning the laten...,"[Before you begin, Key resources table, Step-b...",[Before you begin Stimuli 1. To create a socia...,[limitations]
...,...,...,...,...,...,...,...,...,...,...,...,...
184086,research-article,None,STAR Protocols,PMC8672044,34950882.0,Induction of input-specific spine shrinkage on...,United States of America,11-12-2021,Summary Shrinkage and loss of dendritic spines...,"[Before you begin, Key resources table, Materi...",[Before you begin The protocol below describes...,[limitations]
184199,research-article,None,STAR Protocols,PMC8243151,34223199.0,"Ultracentrifugal separation, characterization,...",Japan,23-6-2021,Summary Extracellular vesicles (EVs) play impo...,"[Before you begin, Key resources table, Materi...",[Before you begin EVs are vesicles naturally s...,[limitations]
184248,research-article,None,STAR Protocols,PMC8882418,NaN,SARS-CoV-2 proteome microarray for COVID-19 pa...,China,28-2-2022,Summary The immunogenicity of severe acute res...,"[Before you begin, Key resources table, Materi...",[Before you begin This protocol was used in a ...,[limitations]
184725,research-article,None,STAR Protocols,PMC8379521,34458864.0,Annotating cell types in human single-cell RNA...,United States of America,17-8-2021,Summary Cell type annotation is important in t...,"[Before you begin, Key resources table, Step-b...",[Before you begin Cell type annotation is an i...,[limitations]
185158,research-article,None,STAR Protocols,PMC8769939,NaN,Transcriptome profiling of PBMCs and formalin-...,United States of America,20-1-2022,Summary Here we present an optimized protocol ...,"[Before you begin, Key resources table, Materi...",[Before you begin The protocol below has been ...,[limitations]

In [ ]:
def get_alt_title(title: str, title_versions: dict) -> str:
    
    # sections we're not interested in
    ignore_list = ['supplementary', 'admin', 'combined', 'misc'] 
    
    # if title is not in the inclusion list, set to empty string
    alt = ''
    for key, synonyms in title_versions.items():
        if key in ignore_list:
            continue
        if not title == None:
            # clean title
            for pat, repl in tv.title_clean.items():
                title = re.sub(pat, repl, title)
            title = title.strip(':').strip()
            if title.casefold() in synonyms:
                alt = key
    return alt

In [8]:
def replace_section_titles(title_versions: dict, section_titles):

    alt_titles = [[get_alt_title(title, title_versions) for title in secs] 
                    for secs in section_titles]
    alt_titles = [[title for title in sorted(secs) if not title == '']
                  for secs in alt_titles]

    return alt_titles

In [9]:
baseline_df['section_titles_cleaned'] = replace_section_titles(tv.title_versions, list(baseline_df['section_titles']))

In [10]:
for i in range(10, 20):
    print(f'before: {baseline_df['section_titles'].iloc[i]}')
    print(f'after: {baseline_df['section_titles_cleaned'].iloc[i]}')

before: ['Le polysulfate de pentosan est le principal traitement de la douleur vésicale associée à la cystite interstitielle', 'La maculopathie est associée à une utilisation prolongée du polysulfate de pentosan', 'La maculopathie causée par le polysulfate de pentosan peut s’apparenter à la dégénérescence maculaire liée à l’âge', 'La maladie maculaire peut poursuivre sa progression malgré l’arrêt du polysulfate de pentosan', 'Les patients exposés au polysulfate de pentosan qui rapportent des troubles de la vision devraient subir un dépistage ophtalmique']
after: []
before: ['INTRODUCTION', 'BACKGROUND', 'THE STUDY', 'RESULTS', 'DISCUSSION', 'CONCLUSIONS', 'CONFLICT OF INTEREST', 'AUTHOR CONTRIBUTIONS', 'ETHICAL APPROVAL AND PATIENT CONSENT\u202fFOR PUBLICATION\u202fSTATEMENT']
after: ['background', 'conclusion', 'discussion', 'introduction', 'results']
before: []
after: []
before: ['Introduction', 'Case Report', 'Discussion']
after: ['case report', 'discussion', 'introduction']
before: ['INTRODUCTION', 'MATERIALS AND METHODS', 'RESULTS', 'DISCUSSION', 'CONCLUSION']
after: ['conclusion', 'discussion', 'introduction', 'methods', 'results']
before: []
after: []
before: ['Introduction', 'Physicochemical Properties of Diosgenin', 'Sources of Diosgenin', 'The Pharmacological Mechanism Underlying the Use of Diosgenin for Treatment of Hyperlipidemia', 'Advantages and Limitations of Diosgenin', 'Conclusion and Future Prospects']
after: ['introduction']
before: ['INTRODUCTION', 'MATERIALS AND METHODS', 'RESULTS', 'DISCUSSION', 'DISCLOSURE', 'Supporting information']
after: ['discussion', 'introduction', 'methods', 'results']
before: []
after: []
before: ['Discussion', 'Trial Information', 'Drug Information', 'Patient Characteristics', 'Primary Assessment Method', 'Adverse Events', 'Serious Adverse Events', 'Assessment, Analysis, and Discussion', 'Disclosures', 'Figures and Tables']
after: ['discussion']

In [11]:
Counter(map(str, baseline_df['section_titles_cleaned']))

Counter({"['conclusion', 'discussion', 'introduction', 'methods', 'results']": 38846,
         "['discussion', 'introduction', 'methods', 'results']": 37718,
         '[]': 29835,
         "['conclusion', 'introduction']": 11543,
         "['case report', 'conclusion', 'discussion', 'introduction']": 6265,
         "['discussion', 'methods', 'results']": 6056,
         "['case report', 'discussion', 'introduction']": 5530,
         "['conclusion', 'introduction', 'methods']": 5089,
         "['conclusion', 'discussion', 'methods', 'results']": 4634,
         "['conclusion', 'experiment', 'introduction']": 3445,
         "['introduction']": 3129,
         "['conclusion']": 2094,
         "['background', 'conclusion', 'discussion', 'methods', 'results']": 1992,
         "['conclusion', 'discussion', 'introduction', 'limitations', 'methods', 'results']": 1953,
         "['discussion', 'introduction']": 1546,
         "['introduction', 'methods']": 1532,
         "['conclusion', 'discussion', 'introduction']": 1324,
         "['case report', 'conclusion', 'diagnosis', 'discussion', 'introduction', 'outcome', 'treatment']": 941,
         "['discussion']": 918,
         "['conclusion', 'discussion', 'introduction', 'results']": 874,
         "['discussion', 'introduction', 'results']": 788,
         "['background', 'case report', 'conclusion', 'discussion']": 787,
         "['case report', 'discussion']": 752,
         "['limitations']": 679,
         "['background', 'discussion', 'methods', 'results']": 665,
         "['conclusion', 'introduction', 'methods', 'results']": 621,
         "['case report', 'conclusion', 'discussion']": 609,
         "['introduction', 'methods', 'results']": 588,
         "['discussion', 'introduction', 'methods']": 585,
         "['conclusion', 'discussion', 'introduction', 'methods']": 572,
         "['discussion', 'experiment', 'introduction', 'results']": 497,
         "['conclusion', 'discussion', 'introduction', 'introduction', 'methods', 'results']": 464,
         "['background', 'conclusion', 'discussion', 'introduction', 'methods', 'results']": 398,
         "['conclusion', 'discussion', 'introduction', 'methods', 'methods', 'results']": 392,
         "['methods', 'methods']": 383,
         "['case report', 'introduction']": 381,
         "['discussion', 'experiment', 'results']": 368,
         "['conclusion', 'discussion']": 352,
         "['conclusion', 'introduction', 'results']": 348,
         "['methods']": 342,
         "['introduction', 'summary']": 298,
         "['methods', 'results']": 291,
         "['case report', 'conclusion', 'diagnosis', 'discussion']": 280,
         "['conclusion', 'discussion', 'experiment', 'introduction', 'results']": 274,
         "['background', 'conclusion']": 262,
         "['discussion', 'introduction', 'limitations', 'methods', 'results']": 260,
         "['conclusion', 'methods']": 259,
         "['conclusion', 'diagnosis', 'discussion']": 233,
         "['conclusion', 'conclusion', 'introduction']": 231,
         "['case report']": 230,
         "['background', 'discussion', 'introduction', 'methods', 'results']": 225,
         "['discussion', 'introduction', 'methods', 'methods', 'results']": 222,
         "['conclusion', 'discussion', 'limitations', 'methods', 'results']": 216,
         "['background', 'conclusion', 'discussion', 'limitations', 'methods', 'results']": 161,
         "['case report', 'conclusion', 'introduction']": 150,
         "['background']": 145,
         "['discussion', 'results']": 144,
         "['background', 'case report', 'discussion', 'outcome', 'treatment']": 140,
         "['summary']": 140,
         "['background', 'case report', 'discussion']": 121,
         "['background', 'conclusion', 'introduction']": 110,
         "['discussion', 'methods']": 106,
         "['conclusion', 'introduction', 'treatment']": 100,
         "['discussion', 'introduction', 'methods', 'results', 'summary']": 100,
         "['conclusion', 'methods', 'results']": 94,
         "['background', 'discussion']": 93,
         "['conclusion', 'diagnosis', 'introduction']": 91,
         "['case report', 'conclusion']": 89,
         "['experiment', 'introduction']": 87,
         "['background', 'conclusion', 'methods', 'results']": 85,
         "['conclusion', 'introduction', 'limitations']": 84,
         "['background', 'discussion', 'methods']": 84,
         "['background', 'conclusion', 'introduction', 'methods']": 84,
         "['introduction', 'results']": 78,
         "['conclusion', 'discussion', 'introduction', 'limitations', 'methods', 'methods', 'results']": 75,
         "['discussion', 'introduction', 'limitations', 'methods', 'results', 'summary']": 75,
         "['background', 'conclusion', 'discussion', 'introduction', 'results']": 72,
         "['background', 'conclusion', 'results']": 71,
         "['conclusion', 'discussion', 'results']": 66,
         "['conclusion', 'diagnosis', 'introduction', 'treatment']": 64,
         "['background', 'case report']": 63,
         "['background', 'case report', 'diagnosis', 'discussion', 'outcome', 'treatment']": 61,
         "['case report', 'conclusion', 'discussion', 'introduction', 'methods']": 61,
         "['background', 'conclusion', 'discussion', 'results']": 58,
         "['background', 'conclusion', 'discussion']": 55,
         "['diagnosis']": 54,
         "['conclusion', 'experiment']": 50,
         "['case report', 'conclusion', 'discussion', 'introduction', 'results']": 50,
         "['background', 'conclusion', 'methods']": 49,
         "['conclusion', 'conclusion', 'discussion', 'introduction', 'methods', 'results']": 48,
         "['background', 'methods', 'results']": 47,
         "['discussion', 'introduction', 'introduction', 'methods', 'results']": 47,
         "['case report', 'discussion', 'introduction', 'summary']": 46,
         "['introduction', 'methods', 'summary']": 46,
         "['conclusion', 'discussion', 'methods']": 43,
         "['background', 'conclusion', 'discussion', 'introduction', 'limitations', 'methods', 'results']": 43,
         "['background', 'methods']": 42,
         "['conclusion', 'introduction', 'summary']": 42,
         "['conclusion', 'experiment', 'introduction', 'results']": 40,
         "['experiment']": 40,
         "['conclusion', 'conclusion', 'discussion', 'introduction', 'limitations', 'methods', 'results']": 39,
         "['conclusion', 'discussion', 'introduction', 'limitations', 'results']": 39,
         "['conclusion', 'introduction', 'methods', 'methods']": 38,
         "['background', 'conclusion', 'introduction', 'methods', 'results']": 37,
         "['background', 'case report', 'discussion', 'outcome']": 36,
         "['introduction', 'introduction']": 36,
         "['conclusion', 'results']": 36,
         "['conclusion', 'conclusion']": 35,
         "['conclusion', 'introduction', 'limitations', 'methods']": 34,
         "['conclusion', 'discussion', 'introduction', 'methods', 'results', 'summary']": 34,
         "['background', 'introduction']": 34,
         "['background', 'conclusion', 'discussion', 'introduction']": 33,
         "['discussion', 'introduction', 'summary']": 32,
         "['background', 'conclusion', 'discussion', 'methods']": 31,
         "['discussion', 'methods', 'methods', 'results']": 31,
         "['case report', 'discussion', 'introduction', 'methods']": 30,
         "['results']": 29,
         "['conclusion', 'discussion', 'methods', 'methods', 'results']": 29,
         "['conclusion', 'discussion', 'experiment', 'results']": 28,
         "['background', 'introduction', 'methods']": 27,
         "['case report', 'diagnosis']": 27,
         "['case report', 'discussion', 'introduction', 'methods', 'results']": 26,
         "['discussion', 'introduction', 'introduction']": 26,
         "['conclusion', 'experiment', 'introduction', 'methods']": 25,
         "['introduction', 'limitations']": 25,
         "['conclusion', 'discussion', 'introduction', 'introduction', 'limitations', 'methods', 'results']": 25,
         "['conclusion', 'discussion', 'introduction', 'limitations', 'methods']": 25,
         "['background', 'introduction', 'methods', 'results']": 24,
         "['case report', 'conclusion', 'discussion', 'introduction', 'methods', 'results']": 24,
         "['conclusion', 'discussion', 'introduction', 'introduction', 'methods', 'results', 'summary']": 24,
         "['background', 'conclusion', 'discussion', 'methods', 'methods', 'results']": 24,
         "['case report', 'discussion', 'introduction', 'results']": 22,
         "['background', 'conclusion', 'discussion', 'introduction', 'methods']": 22,
         "['experiment', 'introduction', 'results']": 22,
         "['conclusion', 'discussion', 'introduction', 'limitations']": 21,
         "['background', 'discussion', 'results']": 21,
         "['conclusion', 'discussion', 'experiment', 'introduction']": 20,
         "['conclusion', 'limitations']": 20,
         "['conclusion', 'introduction', 'outcome']": 20,
         "['background', 'case report', 'conclusion', 'discussion', 'introduction']": 19,
         "['background', 'conclusion', 'introduction', 'results']": 18,
         "['background', 'discussion', 'introduction', 'methods']": 18,
         "['discussion', 'introduction', 'introduction', 'methods']": 18,
         "['discussion', 'limitations', 'methods', 'results']": 18,
         "['conclusion', 'diagnosis']": 17,
         "['case report', 'conclusion', 'diagnosis', 'discussion', 'introduction']": 17,
         "['introduction', 'treatment']": 17,
         "['conclusion', 'introduction', 'limitations', 'methods', 'results']": 16,
         "['case report', 'introduction', 'methods']": 15,
         "['case report', 'diagnosis', 'discussion']": 14,
         "['background', 'conclusion', 'experiment', 'introduction']": 14,
         "['conclusion', 'introduction', 'introduction']": 14,
         "['introduction', 'limitations', 'methods']": 14,
         "['background', 'case report', 'conclusion']": 14,
         "['conclusion', 'introduction', 'introduction', 'methods', 'results']": 14,
         "['background', 'discussion', 'limitations', 'methods', 'results']": 13,
         "['conclusion', 'treatment']": 13,
         "['case report', 'conclusion', 'discussion', 'introduction', 'limitations']": 13,
         "['diagnosis', 'discussion']": 13,
         "['discussion', 'introduction', 'methods', 'summary']": 13,
         "['background', 'summary']": 13,
         "['background', 'conclusion', 'discussion', 'introduction', 'introduction', 'methods', 'results']": 13,
         "['discussion', 'experiment', 'experiment', 'introduction']": 13,
         "['introduction', 'outcome']": 12,
         "['conclusion', 'discussion', 'introduction', 'introduction', 'methods']": 12,
         "['background', 'discussion', 'methods', 'results', 'summary']": 12,
         "['diagnosis', 'introduction']": 12,
         "['background', 'background', 'conclusion']": 12,
         "['conclusion', 'introduction', 'methods', 'methods', 'results']": 11,
         "['conclusion', 'discussion', 'introduction', 'methods', 'methods', 'methods', 'results']": 11,
         "['conclusion', 'diagnosis', 'discussion', 'introduction']": 11,
         "['conclusion', 'introduction', 'introduction', 'methods']": 11,
         "['conclusion', 'discussion', 'introduction', 'methods', 'results', 'results']": 11,
         "['background', 'discussion', 'introduction']": 11,
         "['conclusion', 'discussion', 'introduction', 'methods', 'outcome', 'results']": 11,
         "['discussion', 'introduction', 'methods', 'methods']": 11,
         "['diagnosis', 'introduction', 'treatment']": 11,
         "['conclusion', 'conclusion', 'introduction', 'methods']": 11,
         "['background', 'conclusion', 'discussion', 'introduction', 'limitations', 'results']": 11,
         "['discussion', 'methods', 'results', 'summary']": 10,
         "['conclusion', 'discussion', 'introduction', 'treatment']": 10,
         "['background', 'discussion', 'introduction', 'results']": 10,
         "['introduction', 'methods', 'methods']": 10,
         "['discussion', 'introduction', 'methods', 'results', 'results']": 10,
         "['introduction', 'limitations', 'methods', 'results']": 10,
         "['background', 'conclusion', 'conclusion']": 10,
         "['background', 'case report', 'conclusion', 'discussion', 'outcome', 'treatment']": 10,
         "['conclusion', 'discussion', 'experiment', 'experiment', 'introduction']": 9,
         "['conclusion', 'diagnosis', 'treatment']": 9,
         "['experiment', 'introduction', 'summary']": 9,
         "['background', 'discussion', 'methods', 'methods', 'results']": 9,
         "['case report', 'discussion', 'methods', 'results']": 9,
         "['conclusion', 'introduction', 'methods', 'treatment']": 9,
         "['case report', 'summary']": 9,
         "['case report', 'conclusion', 'discussion', 'introduction', 'treatment']": 9,
         "['case report', 'conclusion', 'discussion', 'introduction', 'outcome', 'treatment']": 8,
         "['discussion', 'introduction', 'treatment']": 8,
         "['treatment']": 8,
         "['outcome']": 8,
         "['discussion', 'introduction', 'methods', 'outcome', 'results']": 7,
         "['introduction', 'introduction', 'methods']": 7,
         "['conclusion', 'discussion', 'introduction', 'introduction', 'results']": 7,
         "['background', 'results']": 7,
         "['background', 'introduction', 'results']": 7,
         "['introduction', 'methods', 'methods', 'results']": 7,
         "['background', 'case report', 'diagnosis', 'discussion', 'outcome']": 7,
         "['conclusion', 'discussion', 'introduction', 'limitations', 'methods', 'results', 'summary']": 7,
         "['conclusion', 'diagnosis', 'diagnosis', 'introduction']": 7,
         "['conclusion', 'introduction', 'methods', 'summary']": 7,
         "['conclusion', 'conclusion', 'introduction', 'methods', 'results']": 7,
         "['discussion', 'introduction', 'limitations', 'methods', 'methods', 'results']": 7,
         "['background', 'discussion', 'methods', 'methods']": 7,
         "['case report', 'conclusion', 'discussion', 'methods', 'results']": 6,
         "['conclusion', 'conclusion', 'discussion', 'methods', 'results']": 6,
         "['background', 'case report', 'conclusion', 'introduction']": 6,
         "['discussion', 'summary']": 6,
         "['background', 'methods', 'methods']": 6,
         "['introduction', 'methods', 'results', 'summary']": 6,
         "['conclusion', 'conclusion', 'discussion', 'introduction']": 6,
         "['discussion', 'introduction', 'outcome']": 6,
         "['case report', 'discussion', 'introduction', 'outcome']": 6,
         "['background', 'case report', 'discussion', 'introduction']": 6,
         "['case report', 'discussion', 'results']": 6,
         "['background', 'conclusion', 'conclusion', 'discussion', 'limitations', 'methods', 'results']": 6,
         "['conclusion', 'discussion', 'experiment', 'introduction', 'methods', 'results']": 6,
         "['background', 'discussion', 'introduction', 'limitations', 'methods', 'results']": 5,
         "['conclusion', 'conclusion', 'methods']": 5,
         "['case report', 'conclusion', 'discussion', 'results']": 5,
         "['diagnosis', 'treatment']": 5,
         "['background', 'conclusion', 'introduction', 'limitations']": 5,
         "['conclusion', 'discussion', 'introduction', 'introduction', 'methods', 'methods', 'results']": 5,
         "['conclusion', 'limitations', 'methods']": 5,
         "['conclusion', 'methods', 'methods']": 5,
         "['discussion', 'experiment', 'experiment']": 5,
         "['case report', 'discussion', 'methods']": 5,
         "['methods', 'summary']": 5,
         "['case report', 'diagnosis', 'discussion', 'introduction']": 5,
         "['discussion', 'introduction', 'limitations', 'methods']": 5,
         "['conclusion', 'summary']": 5,
         "['case report', 'conclusion', 'discussion', 'methods']": 5,
         "['case report', 'conclusion', 'discussion', 'introduction', 'outcome']": 5,
         "['introduction', 'limitations', 'summary']": 5,
         "['conclusion', 'conclusion', 'introduction', 'limitations']": 5,
         "['case report', 'conclusion', 'discussion', 'introduction', 'introduction']": 5,
         "['introduction', 'methods', 'treatment']": 5,
         "['discussion', 'introduction', 'limitations', 'results']": 5,
         "['conclusion', 'diagnosis', 'introduction', 'methods', 'treatment']": 4,
         "['background', 'case report', 'conclusion', 'discussion', 'outcome']": 4,
         "['discussion', 'experiment', 'methods', 'results']": 4,
         "['conclusion', 'discussion', 'introduction', 'methods', 'methods']": 4,
         "['background', 'case report', 'discussion', 'treatment']": 4,
         "['case report', 'conclusion', 'introduction', 'methods']": 4,
         "['conclusion', 'discussion', 'introduction', 'summary']": 4,
         "['discussion', 'introduction', 'methods', 'outcome']": 4,
         "['background', 'conclusion', 'limitations', 'methods', 'results']": 4,
         "['background', 'introduction', 'summary']": 4,
         "['conclusion', 'limitations', 'methods', 'results']": 4,
         "['conclusion', 'discussion', 'introduction', 'methods', 'outcome']": 4,
         "['diagnosis', 'discussion', 'introduction']": 4,
         "['case report', 'discussion', 'introduction', 'treatment']": 4,
         "['diagnosis', 'introduction', 'summary', 'treatment']": 4,
         "['conclusion', 'discussion', 'introduction', 'outcome']": 4,
         "['conclusion', 'diagnosis', 'diagnosis', 'introduction', 'treatment']": 4,
         "['case report', 'discussion', 'summary']": 4,
         "['discussion', 'introduction', 'results', 'summary']": 4,
         "['introduction', 'methods', 'outcome']": 4,
         "['conclusion', 'discussion', 'limitations']": 4,
         "['background', 'case report', 'diagnosis', 'discussion']": 3,
         "['discussion', 'introduction', 'methods', 'methods', 'outcome', 'results']": 3,
         "['background', 'conclusion', 'limitations']": 3,
         "['background', 'case report', 'conclusion', 'discussion', 'introduction', 'results']": 3,
         "['background', 'conclusion', 'summary']": 3,
         "['discussion', 'discussion', 'introduction', 'methods', 'results']": 3,
         "['background', 'case report', 'conclusion', 'discussion', 'introduction', 'methods']": 3,
         "['background', 'case report', 'conclusion', 'discussion', 'results']": 3,
         "['diagnosis', 'introduction', 'summary']": 3,
         "['background', 'conclusion', 'methods', 'methods']": 3,
         "['background', 'conclusion', 'experiment', 'introduction', 'methods']": 3,
         "['case report', 'conclusion', 'discussion', 'outcome']": 3,
         "['background', 'conclusion', 'discussion', 'introduction', 'limitations', 'methods']": 3,
         "['introduction', 'introduction', 'summary']": 3,
         "['conclusion', 'discussion', 'limitations', 'results']": 3,
         "['background', 'conclusion', 'limitations', 'results']": 3,
         "['discussion', 'experiment', 'introduction', 'methods', 'results']": 3,
         "['case report', 'conclusion', 'methods']": 3,
         "['case report', 'diagnosis', 'discussion', 'results']": 3,
         "['introduction', 'results', 'summary']": 3,
         "['experiment', 'experiment', 'introduction']": 3,
         "['background', 'discussion', 'methods', 'outcome']": 3,
         "['conclusion', 'conclusion', 'discussion', 'introduction', 'methods']": 3,
         "['conclusion', 'diagnosis', 'introduction', 'methods']": 3,
         "['background', 'conclusion', 'conclusion', 'discussion', 'methods', 'results']": 3,
         "['background', 'conclusion', 'discussion', 'limitations', 'methods']": 3,

In [12]:
# proportion of all papers where no titles were found
len(baseline_df[baseline_df['section_titles'].apply(lambda x: x == [])]) / len(baseline_df)

0.08324260227456476

In [13]:
# proportion of research articles in batch
article_count = len(baseline_df[baseline_df['article-type'] == 'research-article']) 
article_count / len(baseline_df)

0.6443486228642268

In [14]:
# proportion of research articles where no titles were found
len(baseline_df[baseline_df['section_titles'].apply(lambda x: x == [])][baseline_df['article-type'] == 'research-article']) / article_count

/tmp/ipykernel_1114804/1322135802.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  len(baseline_df[baseline_df['section_titles'].apply(lambda x: x == [])][baseline_df['article-type'] == 'research-article']) / article_count

0.00964482291335553

In [15]:
Counter(baseline_df['article-type'])

Counter({'research-article': 119546,
         'case-report': 18783,
         'review-article': 16340,
         'letter': 5391,
         'abstract': 5157,
         'editorial': 4767,
         'brief-report': 4645,
         'other': 4090,
         'correction': 1575,
         'discussion': 1281,
         'article-commentary': 1218,
         'systematic-review': 708,
         'data-paper': 438,
         'news': 395,
         'retraction': 315,
         'reply': 213,
         'rapid-communication': 178,
         'meeting-report': 131,
         'report': 94,
         'book-review': 61,
         'methods-article': 53,
         'obituary': 45,
         'introduction': 39,
         'expression-of-concern': 26,
         'in-brief': 15,
         'product-review': 11,
         'addendum': 9,
         'announcement': 2,
         'oration': 2,
         ' research-article': 1,
         'protocol': 1})